#:schema node_modules/wrangler/config-schema.json
name = "aibtcdev-frontend"
compatibility_date = "2024-11-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "18.20"
NEXT_PUBLIC_API_URL="https://backend-droplet.aibtc.dev"
NEXT_PUBLIC_SITE_URL="https://sprint-faster.aibtc.dev"
