name: Deploy to Cloudflare

on:
  push:
    branches: [feat/cloudflare]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Ship Ship Ship
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
